#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

if [ $# -lt 4 ]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

# Assign the given arguments by the user to variables
file=$1
ip=$2
username=$3
ssh_key=$4

# scp (secure copy) transfer the file and -o disable strict host key checking
scp -o "strictHostKeyChecking=no" -i "$ssh_key" "$path" "$username@$ip:~/"
