#!/usr/bin/env bash
# Install nginx and configure it to listen to port 80
# it must return a page that contains the string Hello World!

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
