#!/usr/bin/env bash
# Fixing Ubuntu container’s Nginx
# installation to listen on port 80
apt install -y nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
