#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid with its PID

echo $$ > "/var/run/myscript.pid"
trap "echo 'I hate the kill command'"; 'rm /var/run/myscript.pid; exit $?' SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap 'rm /var/run/myscript.pid; exit $?' SIGQUIT
while true; do
  echo "To infinity and beyond"
done
