#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid with its PID
del='rm /var/run/myscript.pid'

echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command"; '"$del" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap ''"$del" SIGQUIT

while true; do
  echo "To infinity and beyond"
done
