#!/usr/bin/env bash
# Installed ufw with few rules: block all
# incoming trafic except at ports 22, 443 and 8

sudo apt update
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tc
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
