#!/usr/bin/bash
# This script connects to the server using SSH with a private key.

# Specify the server IP address and the username
SERVER_IP="52.3.244.51"
USERNAME="ubuntu"

# Use SSH with the private key
ssh -i ~/.ssh/school "$USERNAME@$SERVER_IP"
